#Pick intrinsic fns as u need: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference.html
Resources:
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-467ca739 # Amazon Linux AMI in N.Virginia
      Tags:
        - Key: Name
          Value: !Join [ "", [ EC2, Instance, with, Fn, Join]]
#Syntax: Fn::Join: [ delimiter, [ comma-delimited list of values ] ]
